#!/bin/bash

# Filepath: $HOME/.config/scripts/wallpaper.share
# creator: zephar 
# github: https://github.com/ZepharDev
# In process


dir="$HOME/.local/share/wallpapers"
config="$HOME/.config/hypr/hyprpaper.conf"
cache="$HOME/.cache/hypr"
last_wall="$cache/last_wallpaper"

# --- Create directory if it does not exist --

mkdir -p "$cache"

error_handler() {
  notify-send "Error" "Unable to set the wallpaper": $1
  exit 1
} 

# Check neccesary directories and files
# Directory $HOME/.local/share/wallpaper
# Verify the presence of image files in the directory

[ ! -d "$dir" ] && error_handler "Directory of wallpaper found"
[ ! -d "$(dirname "$config")" ] && error_handler "Directory of configuration no found"

wall=$(find "$dir" -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \) -printf "%f\n" | \
     rofi -dmenu -theme ~/.config/rofi/wallpaper.rasi -i -p "Wallpapers" -theme-str 'window {width: 50%;}')

# verify 
[ -z "$wall" ] && exit 0

# Write 

wall_path="$dir/$wall"
[ ! -f "$wall_path" ] && error_handler "Archive no found"

# HELPPPPP
# monitor active

monitor="$(hyprctl monitors -j | jq -r '.[].name')"

# Create new config hyprpaper, new date

{
  echo "# --- Configuration generated by wallpaper.sh"
  echo "preload = $wall_path"
  echo ""
  for monitor in $monitor; do 
    echo "wallpaper = $monitor,$wall_path"
  done
} > "$config"

echo "$wall_path" > "$last_wall"


# help please, not found my neuron
#
if pgrep -x hyprpaper > /dev/null; then
    pkill -SIGUSR2 hyprpaper || {
        pkill hyprpaper
        sleep 0.1
        hyprpaper &
    }
else
    hyprpaper &
fi

# Verificación final
sleep 1
if pgrep -x hyprpaper > /dev/null; then
    notify-send "wallpaper applied correctly" "$(basename "$wall_path")" -i "$wall_path"
else
    error_handler "No se pudo aplicar el wallpaper"
fi
