#!/bin/bash 

# Creator: zephardev
# Repository: https://github.com/zephardev
# Script to select wallpapers
# Optimized script to change wallpapers faster
# The configuration is located at: ~/.config/rofi/wallpapers.rasi
# This uses hyprpaper
# Advertence: The script may have bugsç
# WO proyect: Workflow optimization

# Directory where we have the wallpapers :D 

wallpaperDir="$HOME/.local/share/wallpapers/"
hyprpaperDir="$HOME/.config/hypr/hyprpaper.conf"
cacheDir="$HOME/.cache/hypr/"
configDir="$HOME/.config/rofi/wallhar.rasi"
wallCache="$cacheDir/wallCache"

# Create directory if is doest not exist 

mkdir -p "$cacheDir"

# Rofi cmd
# Remove this if you don't need it.

user="$(whoami)"
host="$(hostname)"
uptime="$(uptime)"

# And if the directory does not exist? I don't know.
# Create mkdir -p $wallpaperDir
# Example:
# mkdir -p $wallpaperDir 
# Just remove the # and run the script ONCE, or more simply,
# to to the terminal (kitty or any) and type mkdir -p $wallpaperDir
# If you have already cloned the Github repository, you  can do the following
# mv ~/hyprdots/configs/local/wallpapers ~/.local/share/wallpapers/ 

# This list a most wallpapers extensions, Example.jpg
# Name: wallExt

wallExt=$(find "$wallpaperDir" -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" \))

rofi_cmd() {
  rofi -dmenu \
    -p " $user@$host" \
    -config $configDir 
}

# Selected helps us identify which options 
# we have chosen, so we can apply in hyprpaper 

selected=$(echo -e "$wallExt" | while read -r file; do basename "$file"; done | rofi_cmd)

wallPath="$wallpaperDir/$selected"

# Get the monitors active

monitors=$(hyprctl monitors -j | jq -r '.[].name') || error_handler "Error getting monitors"

{
  echo "# Configuration generated by wallhar.sh"
  echo "preload = $wallPath"
  echo ""
  for monitor in $monitors; do 
    echo "wallpaper = $monitors,$wallPath"
  done
} > "$hyprpaperDir"

echo "$wallPath" > "wallCache"

if pgrep -x hyprpaper >/dev/null; then
  pkill -SIGUSR2 hyprpaper || {
    pkill hyprpaper 
    sleep 1
    hyprpaper &
  }
else 
  hyprpaper &
fi

